apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: fizzag/my-flask-app:latest
          ports:   # ✅ Fixed indentation
            - containerPort: 5000
          env:   # ✅ Fixed indentation
            - name: DATABASE_HOST
              value: "postgres-service"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database
