apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: cG9zdGdyZXM=   # "postgres" encoded in Base64
  password: c2VjdXJlcGFzcw==   # "securepass" encoded in Base64
